# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0002_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
