# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0003_auto_20170418_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='location',
        ),
        migrations.AddField(
            model_name='news',
            name='lan',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='news',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
