# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0004_auto_20170418_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='originality',
            field=models.FloatField(default=0.0),
        ),
    ]
